name = "geografie"
main = "worker/index.ts"
compatibility_date = "2025-01-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "geografie-highscores"
database_id = "5afbe659-e330-4af7-b0be-4358d731f0c3"
